name: paintable_text
description: Flutter text painter with advanced features
version: 0.0.1
homepage: https://github.com/swimmingkiim/paintable_text
repository: https://github.com/swimmingkiim/paintable_text
issue_tracker: https://github.com/swimmingkiim/paintable_text/issues

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
